/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-01-30 09:27:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import jakarta.servlet.http.Cookie;
import models.Product_pojo;

public final class products_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("jakarta.servlet.http.Cookie");
    _jspx_imports_classes.add("models.Product_pojo");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    String portId = null;
    Cookie[] cookies = request.getCookies();
    if(cookies != null){
        for(Cookie c : cookies){
            if("port_id".equals(c.getName())){
                portId = c.getValue();
                break;
            }
        }
    }
    if(portId == null){
        response.sendRedirect("login.jsp");
        return;
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Professional Seller Dashboard</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write(":root{\r\n");
      out.write("  --bg1:#0a0214;\r\n");
      out.write("  --primary:#6c2bd9;\r\n");
      out.write("  --primary-600:#5b23c0;\r\n");
      out.write("  --primary-200:#e6dbff;\r\n");
      out.write("  --primary-100:#f6f1ff;\r\n");
      out.write("  --pink:#ff4b91;\r\n");
      out.write("  --ink:#1b1b1b;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Background animation */\r\n");
      out.write("@keyframes gradientShift{\r\n");
      out.write("  0%{background-position:0% 50%}\r\n");
      out.write("  50%{background-position:100% 50%}\r\n");
      out.write("  100%{background-position:0% 50%}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html,body{height:100%}\r\n");
      out.write("body{\r\n");
      out.write("  margin:0;\r\n");
      out.write("  font-family:'Poppins',sans-serif;\r\n");
      out.write("  background:linear-gradient(120deg,#1b1b2f,#162447,#1f4068,#451952);\r\n");
      out.write("  background-size:300% 300%;\r\n");
      out.write("  animation:gradientShift 14s ease infinite;\r\n");
      out.write("  color:var(--ink);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Navbar */\r\n");
      out.write(".navbar{\r\n");
      out.write("  display:flex;\r\n");
      out.write("  justify-content:space-between;\r\n");
      out.write("  align-items:center;\r\n");
      out.write("  background:linear-gradient(90deg,#2a1a5e,#451952);\r\n");
      out.write("  padding:20px 50px;\r\n");
      out.write("  height:100px;\r\n");
      out.write("  position:sticky;\r\n");
      out.write("  top:0;\r\n");
      out.write("  z-index:30;\r\n");
      out.write("  box-shadow:0 4px 20px rgba(0,0,0,.4)\r\n");
      out.write("}\r\n");
      out.write(".navbar .logo{\r\n");
      out.write("  display:flex;\r\n");
      out.write("  align-items:center;\r\n");
      out.write("  font-size:2rem;\r\n");
      out.write("  font-weight:700;\r\n");
      out.write("  color:#ff4b91;\r\n");
      out.write("}\r\n");
      out.write(".navbar .logo img{\r\n");
      out.write("  height:75px;\r\n");
      out.write("  width:75px;\r\n");
      out.write("  margin-right:15px;\r\n");
      out.write("  border-radius:50%;\r\n");
      out.write("  box-shadow:0 4px 15px rgba(255,75,145,.6);\r\n");
      out.write("}\r\n");
      out.write(".nav-links{display:flex;gap:50px}\r\n");
      out.write(".nav-links a{\r\n");
      out.write("  color:#fff;\r\n");
      out.write("  text-decoration:none;\r\n");
      out.write("  font-weight:500;\r\n");
      out.write("  position:relative\r\n");
      out.write("}\r\n");
      out.write(".nav-links a::after{\r\n");
      out.write("  content:'';\r\n");
      out.write("  position:absolute;\r\n");
      out.write("  left:0;\r\n");
      out.write("  bottom:-8px;\r\n");
      out.write("  height:3px;\r\n");
      out.write("  width:0;\r\n");
      out.write("  background:#ff4b91;\r\n");
      out.write("  transition:.3s\r\n");
      out.write("}\r\n");
      out.write(".nav-links a:hover{color:#ff4b91}\r\n");
      out.write(".nav-links a:hover::after{width:100%}\r\n");
      out.write("\r\n");
      out.write(".btn-profile{\r\n");
      out.write("  padding:10px 20px;\r\n");
      out.write("  border-radius:12px;\r\n");
      out.write("  font-weight:700;\r\n");
      out.write("  background:linear-gradient(135deg,#ff00cc,#3333ff);\r\n");
      out.write("  color:#fff;\r\n");
      out.write("  text-decoration:none;\r\n");
      out.write("  box-shadow:0 0 12px rgba(255,0,204,.6);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* MAIN SHEET */\r\n");
      out.write(".sheet{\r\n");
      out.write("  width:92%;\r\n");
      out.write("  max-width:1200px;\r\n");
      out.write("  margin:70px auto;\r\n");
      out.write("  background:#fff;\r\n");
      out.write("  border:2px solid var(--primary);\r\n");
      out.write("  border-radius:18px;\r\n");
      out.write("  box-shadow:0 20px 60px rgba(0,0,0,.35);\r\n");
      out.write("  overflow:hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Header */\r\n");
      out.write(".sheet-head{\r\n");
      out.write("  background:linear-gradient(90deg,var(--primary),#8b5cf6);\r\n");
      out.write("  color:#fff;\r\n");
      out.write("  padding:20px;\r\n");
      out.write("  text-align:center;\r\n");
      out.write("  font-size:1.3rem;\r\n");
      out.write("  font-weight:800;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Cards */\r\n");
      out.write(".card{\r\n");
      out.write("  background:#fff;\r\n");
      out.write("  border-radius:16px;\r\n");
      out.write("  box-shadow:0 10px 30px rgba(0,0,0,.15);\r\n");
      out.write("  border:1.5px solid var(--primary-200);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-header{\r\n");
      out.write("  background:linear-gradient(90deg,var(--primary),#8b5cf6);\r\n");
      out.write("  color:#fff;\r\n");
      out.write("  border-radius:16px 16px 0 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Form */\r\n");
      out.write(".form-control, textarea{\r\n");
      out.write("  border-radius:12px;\r\n");
      out.write("  border:1.5px solid var(--primary-200);\r\n");
      out.write("}\r\n");
      out.write(".form-control:focus{\r\n");
      out.write("  border-color:var(--primary);\r\n");
      out.write("  box-shadow:0 0 0 .15rem rgba(108,43,217,.25);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Buttons */\r\n");
      out.write(".btn{\r\n");
      out.write("  border-radius:12px;\r\n");
      out.write("  font-weight:700;\r\n");
      out.write("}\r\n");
      out.write(".btn-success{\r\n");
      out.write("  background:#22c55e;\r\n");
      out.write("  border:none;\r\n");
      out.write("}\r\n");
      out.write(".btn-warning{\r\n");
      out.write("  background:#facc15;\r\n");
      out.write("  border:none;\r\n");
      out.write("}\r\n");
      out.write(".btn-danger{\r\n");
      out.write("  background:#ef4444;\r\n");
      out.write("  border:none;\r\n");
      out.write("}\r\n");
      out.write(".btn-info{\r\n");
      out.write("  background:#3b82f6;\r\n");
      out.write("  border:none;\r\n");
      out.write("  color:#fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Table */\r\n");
      out.write(".table{\r\n");
      out.write("  border-radius:14px;\r\n");
      out.write("  overflow:hidden;\r\n");
      out.write("}\r\n");
      out.write(".table thead{\r\n");
      out.write("  background:var(--primary-100);\r\n");
      out.write("  color:var(--primary);\r\n");
      out.write("  font-weight:800;\r\n");
      out.write("}\r\n");
      out.write(".table tbody tr:hover{\r\n");
      out.write("  background:#faf7ff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Footer */\r\n");
      out.write("footer{\r\n");
      out.write("  background:#111827;\r\n");
      out.write("  color:#fff;\r\n");
      out.write("  text-align:center;\r\n");
      out.write("  padding:15px;\r\n");
      out.write("  margin-top:40px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"navbar\">\r\n");
      out.write("    <div class=\"logo\">\r\n");
      out.write("        <img src=\"image/logo.png\" alt=\"Logo\">\r\n");
      out.write("        <span>ImportExportERP</span>\r\n");
      out.write("    </div>\r\n");
      out.write("        <div class=\"nav-links\">\r\n");
      out.write("        <a href=\"http://localhost:8080/RegistrationLogin/dashboard.jsp?port_id=");
      out.print( portId );
      out.write("\" class=\"nav-link\">Home</a>\r\n");
      out.write("       <a href=\"http://localhost:8080/ProductManagement/ProductServlet\" class=\"nav-link\">\r\n");
      out.write("    Product Management\r\n");
      out.write("</a>\r\n");
      out.write("        <a href=\"http://localhost:8080/OrderManagement/ListOrdersServlet?seller_port_id=");
      out.print( portId);
      out.write("\" class=\"nav-link\">\r\n");
      out.write("    Order Management\r\n");
      out.write("</a>\r\n");
      out.write("        <a href=\"http://localhost:8080/Report_product/ReportedProductsServlet?port_id=");
      out.print( portId);
      out.write("\" class=\"nav-link\">\r\n");
      out.write("    Reported Products\r\n");
      out.write("</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"nav-cta\">\r\n");
      out.write("        <a href=\"http://localhost:8080/ProfileManagement/ProfileController?port_id=");
      out.print( portId );
      out.write("\" class=\"btn btn-profile\">Profile</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"sheet\">\r\n");
      out.write("  <div class=\"sheet-head\">\r\n");
      out.write("    <i class=\"fa-solid fa-boxes-stacked\"></i> Product Management\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"container my-5\">\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    ");

        String msg = (String) request.getAttribute("message");
        if (msg != null && !msg.isEmpty()) {
    
      out.write("\r\n");
      out.write("        <div class=\"alert ");
      out.print( msg.startsWith("❌") ? "alert-danger" : "alert-success" );
      out.write(" text-center fw-bold rounded-3\">\r\n");
      out.write("            ");
      out.print( msg );
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    ");

        }
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row justify-content-center\">\r\n");
      out.write("        <div class=\"col-lg-8 col-md-10\">\r\n");
      out.write("            <div class=\"card p-4 my-4\">\r\n");
      out.write("                <div class=\"card-header text-center py-4\">\r\n");
      out.write("                    <h3 class=\"mb-0 text-white\">Manage Products</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <form id=\"productForm\" method=\"post\" action=\"ProductServlet\">\r\n");
      out.write("                        <input type=\"hidden\" id=\"port_id\" name=\"port_id\" value=\"");
      out.print( portId );
      out.write("\">\r\n");
      out.write("                        <input type=\"hidden\" id=\"productId\" name=\"productId\">\r\n");
      out.write("                        <!-- Hidden field for original product name -->\r\n");
      out.write("                        <input type=\"hidden\" id=\"original_productname\" name=\"original_productname\">\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <label for=\"productname\" class=\"form-label\">Product Name</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"productname\" name=\"productname\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <label for=\"description\" class=\"form-label\">Description</label>\r\n");
      out.write("                            <textarea class=\"form-control\" id=\"description\" name=\"description\" rows=\"3\"></textarea>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                <label for=\"quantity\" class=\"form-label\">Quantity</label>\r\n");
      out.write("                                <input type=\"number\" class=\"form-control\" id=\"quantity\" name=\"quantity\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                <label for=\"price\" class=\"form-label\">Price</label>\r\n");
      out.write("                                <input type=\"number\" step=\"0.01\" class=\"form-control\" id=\"price\" name=\"price\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"d-flex justify-content-end gap-2 mt-4\">\r\n");
      out.write("                            <input type=\"submit\" class=\"btn btn-success\" name=\"Add\" value=\"Add Product\">\r\n");
      out.write("                              <!-- Hidden actual submit buttons -->\r\n");
      out.write("    <input type=\"submit\" name=\"Update\" value=\"Update Product\" style=\"display:none;\">\r\n");
      out.write("    <input type=\"submit\" name=\"Delete\" value=\"Delete Product\" style=\"display:none;\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Visible buttons to trigger modal -->\r\n");
      out.write("    <input type=\"button\" class=\"btn btn-warning\" value=\"Update Product\" onclick=\"showConfirm('update')\">\r\n");
      out.write("    <input type=\"button\" class=\"btn btn-danger\" value=\"Delete Product\" onclick=\"showConfirm('delete')\">\r\n");
      out.write("</div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    <!-- Confirmation Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"confirmModal\" tabindex=\"-1\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header bg-warning text-dark\">\r\n");
      out.write("        <h5 class=\"modal-title\">Confirm Action</h5>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <p id=\"modalMessage\">Are you sure you want to perform this action?</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-primary\" id=\"modalConfirmBtn\">Yes</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <div class=\"card p-4 mt-5 mb-5\">\r\n");
      out.write("        <div class=\"card-header text-center py-4\">\r\n");
      out.write("            <h3 class=\"mb-0 text-white\">Product List</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("            <div class=\"table-responsive\">\r\n");
      out.write("                <table class=\"table table-hover table-bordered align-middle\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>Port ID</th>\r\n");
      out.write("                            <th>Product Name</th>\r\n");
      out.write("                            <th>Description</th>\r\n");
      out.write("                            <th>Quantity</th>\r\n");
      out.write("                            <th>Price</th>\r\n");
      out.write("                            <th>Actions</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody class=\"table-light\">\r\n");
      out.write("                        ");

                            List<Product_pojo> products = (List<Product_pojo>) request.getAttribute("products");
                            if (products != null) {
                                for (Product_pojo product : products) {
                        
      out.write("\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>");
      out.print( product.getSeller_port_id() );
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print( product.getProductname() );
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print( product.getDescription() );
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print( product.getQuantity() );
      out.write("</td>\r\n");
      out.write("                            <td>₹ ");
      out.print( product.getPrice() );
      out.write("</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <button class=\"btn btn-info btn-sm\"\r\n");
      out.write("                                    onclick=\"populateForm('");
      out.print( product.getSeller_port_id() );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print( product.getProductId() );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print( product.getProductname().replace("'", "\\'") );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print( product.getDescription().replace("'", "\\'") );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print( product.getQuantity() );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print( product.getPrice() );
      out.write("')\">\r\n");
      out.write("                                    <i class=\"fa-solid fa-pen-to-square\"></i> Edit\r\n");
      out.write("                                </button>\r\n");
      out.write("                                \r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        ");

                                }
                            } else {
                        
      out.write("\r\n");
      out.write("                        <tr><td colspan=\"6\" class=\"text-center\">No products found. Add a new product above.</td></tr>\r\n");
      out.write("                        ");

                            }
                        
      out.write("\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <p class=\"mb-0\">© 2024 PRODUCT MANAGEMENT. All Rights Reserved.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("function populateForm(portId, productId, productName, description, quantity, price){\r\n");
      out.write("    document.getElementById('port_id').value = portId;\r\n");
      out.write("    document.getElementById('productId').value = productId;\r\n");
      out.write("    document.getElementById('productname').value = productName;\r\n");
      out.write("    document.getElementById('original_productname').value = productName; // store original name\r\n");
      out.write("    document.getElementById('description').value = description;\r\n");
      out.write("    document.getElementById('quantity').value = quantity;\r\n");
      out.write("    document.getElementById('price').value = price;\r\n");
      out.write("    window.scrollTo({top:0, behavior:'smooth'});\r\n");
      out.write("}\r\n");
      out.write("let actionType = '';\r\n");
      out.write("\r\n");
      out.write("function showConfirm(action){\r\n");
      out.write("    actionType = action;\r\n");
      out.write("    document.getElementById('modalMessage').textContent =\r\n");
      out.write("        action === 'update' ? 'Are you sure you want to update this product?' :\r\n");
      out.write("                              'Are you sure you want to delete this product?';\r\n");
      out.write("    const confirmModal = new bootstrap.Modal(document.getElementById('confirmModal'));\r\n");
      out.write("    confirmModal.show();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("document.getElementById('modalConfirmBtn').addEventListener('click', function(){\r\n");
      out.write("    const form = document.getElementById('productForm');\r\n");
      out.write("    if(actionType === 'update') form.querySelector('input[name=\"Update\"]').click();\r\n");
      out.write("    else if(actionType === 'delete') form.querySelector('input[name=\"Delete\"]').click();\r\n");
      out.write("    const confirmModal = bootstrap.Modal.getInstance(document.getElementById('confirmModal'));\r\n");
      out.write("    confirmModal.hide();\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
