/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2025-08-23 13:32:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Imp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Import Export ERP System</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("    /* Gradient background same as order.jsp */\r\n");
      out.write("    body {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        font-family: 'Poppins', sans-serif;\r\n");
      out.write("        height: 100vh;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        background: linear-gradient(120deg, #1b1b2f, #162447, #1f4068);\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Floating card */\r\n");
      out.write("    .erp-card {\r\n");
      out.write("        background: rgba(0,0,0,0.6);\r\n");
      out.write("        border-radius: 25px;\r\n");
      out.write("        padding: 60px 40px;\r\n");
      out.write("        max-width: 500px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        box-shadow: 0 15px 40px rgba(0,0,0,0.6);\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        animation: fadeInUp 1s ease forwards;\r\n");
      out.write("        transform: translateY(50px);\r\n");
      out.write("        opacity: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes fadeInUp {\r\n");
      out.write("        to { transform: translateY(0); opacity: 1; }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .erp-card h1 {\r\n");
      out.write("        font-size: 2.8rem;\r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("        color: #ff4b91;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("        text-shadow: 0 2px 10px rgba(0,0,0,0.3);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .erp-card p {\r\n");
      out.write("        font-size: 1.2rem;\r\n");
      out.write("        margin-bottom: 40px;\r\n");
      out.write("        line-height: 1.5;\r\n");
      out.write("        color: #f1f1f1;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-register {\r\n");
      out.write("        background-color: #ff4b91;\r\n");
      out.write("        border: none;\r\n");
      out.write("        padding: 15px 30px;\r\n");
      out.write("        font-size: 1.1rem;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        border-radius: 12px;\r\n");
      out.write("        transition: all 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-register:hover {\r\n");
      out.write("        background-color: #ff2e75;\r\n");
      out.write("        transform: scale(1.05);\r\n");
      out.write("        box-shadow: 0 8px 20px rgba(0,0,0,0.4);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Decorative animated dots */\r\n");
      out.write("    .dot {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        border-radius: 50%;\r\n");
      out.write("        background: rgba(255,75,145,0.2);\r\n");
      out.write("        animation: float 6s infinite;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes float {\r\n");
      out.write("        0% { transform: translateY(0) rotate(0deg);}\r\n");
      out.write("        50% { transform: translateY(-30px) rotate(180deg);}\r\n");
      out.write("        100% { transform: translateY(0) rotate(360deg);}n\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dot1 { width: 100px; height: 100px; top: 10%; left: 5%; animation-delay: 0s; }\r\n");
      out.write("    .dot2 { width: 150px; height: 150px; top: 70%; left: 70%; animation-delay: 2s; }\r\n");
      out.write("    .dot3 { width: 80px; height: 80px; top: 50%; left: 30%; animation-delay: 4s; }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Decorative Floating Dots -->\r\n");
      out.write("<div class=\"dot dot1\"></div>\r\n");
      out.write("<div class=\"dot dot2\"></div>\r\n");
      out.write("<div class=\"dot dot3\"></div>\r\n");
      out.write("\r\n");
      out.write("<!-- ERP Card -->\r\n");
      out.write("<div class=\"erp-card\">\r\n");
      out.write("    <h1>Import Export ERP System</h1>\r\n");
      out.write("    <p>Manage your imports, exports, orders, products, and reports all in one place with real-time insights and analytics.</p>\r\n");
      out.write("    <a href=\"register.jsp\" class=\"btn btn-register\">Register</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
