/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2025-08-24 14:33:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	font-family: 'Poppins', sans-serif;\r\n");
      out.write("	height: 100vh;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	background: #f0f2f5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".left-blog {\r\n");
      out.write("	flex: 1.2;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	padding: 50px;\r\n");
      out.write("	background: linear-gradient(120deg, #1b1b2f, #162447, #1f4068);\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".left-blog h1 {\r\n");
      out.write("	font-size: 3rem;\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("	color: #ff4b91;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".left-blog p {\r\n");
      out.write("	font-size: 1.2rem;\r\n");
      out.write("	max-width: 400px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".right-form {\r\n");
      out.write("	flex: 0.8;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	padding: 50px;\r\n");
      out.write("	background: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-card {\r\n");
      out.write("	background: linear-gradient(120deg, #1b1b2f, #162447, #1f4068);\r\n");
      out.write("	border-radius: 20px;\r\n");
      out.write("	padding: 40px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	max-width: 400px;\r\n");
      out.write("	box-shadow: 0 10px 25px rgba(0, 0, 0, 0.4);\r\n");
      out.write("	color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-card h2 {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin-bottom: 25px;\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("	color: #ff4b91;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-label {\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control {\r\n");
      out.write("	background: rgba(255, 255, 255, 0.05);\r\n");
      out.write("	border: 1px solid rgba(255, 255, 255, 0.3);\r\n");
      out.write("	border-radius: 12px;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	margin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control:focus {\r\n");
      out.write("	border-color: #ff4b91;\r\n");
      out.write("	box-shadow: 0 0 8px #ff4b91;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-custom {\r\n");
      out.write("	background-color: #ff4b91;\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-radius: 12px;\r\n");
      out.write("	padding: 12px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-custom:hover {\r\n");
      out.write("	background-color: #ff2e75;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".errorBox {\r\n");
      out.write("	background: #ffdddd;\r\n");
      out.write("	color: #d60000;\r\n");
      out.write("	border: 1px solid #ff0000;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	margin-bottom: 15px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".back-btn {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	padding: 8px 20px;\r\n");
      out.write("	background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("	color: #ff4b91;\r\n");
      out.write("	border: 1px solid #ff4b91;\r\n");
      out.write("	border-radius: 12px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	transition: all 0.3s ease;\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".back-btn:hover {\r\n");
      out.write("	background: #ff4b91;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	border-color: #ff4b91;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"left-blog\">\r\n");
      out.write("		<h1>Welcome Back!</h1>\r\n");
      out.write("		<p>Login to your dashboard and manage orders, products, and\r\n");
      out.write("			reports seamlessly.</p>\r\n");
      out.write("\r\n");
      out.write("		<!-- Added Image -->\r\n");
      out.write("		<img\r\n");
      out.write("			src=\"https://cdni.iconscout.com/illustration/premium/thumb/employee-enters-details-on-login-page-illustration-svg-png-download-8869756.png\"\r\n");
      out.write("			alt=\"Login Illustration\" class=\"img-fluid mt-4 rounded shadow\"\r\n");
      out.write("			style=\"max-width: 350px;\">\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"right-form\">\r\n");
      out.write("		<div class=\"login-card\">\r\n");
      out.write("\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("			");

			String loginError = (String) request.getAttribute("loginError");
			if (loginError != null) {
			
      out.write("\r\n");
      out.write("			<div class=\"errorBox\">");
      out.print(loginError);
      out.write("</div>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<h2>Login</h2>\r\n");
      out.write("			<form action=\"LoginServlet\" method=\"post\">\r\n");
      out.write("				<div>\r\n");
      out.write("					<label for=\"port_id\" class=\"form-label\">Port ID</label> <input\r\n");
      out.write("						type=\"text\" class=\"form-control\" id=\"port_id\" name=\"port_id\"\r\n");
      out.write("						required>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div style=\"position: relative;\">\r\n");
      out.write("					<label for=\"password\" class=\"form-label\">Password</label> <input\r\n");
      out.write("						type=\"password\" class=\"form-control\" id=\"password\" name=\"password\"\r\n");
      out.write("						required> <i class=\"bi bi-eye-fill\" id=\"togglePassword\"\r\n");
      out.write("						style=\"position: absolute; right: 12px; top: 38px; cursor: pointer; color: #ff4b91;\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("				<button type=\"submit\" class=\"btn btn-custom mt-3\">Login</button>\r\n");
      out.write("			</form>\r\n");
      out.write("			<div style=\"text-align: center;\">\r\n");
      out.write("				<a href=\"register.jsp\" class=\"back-btn\"><i\r\n");
      out.write("					class=\"fas fa-arrow-left\"></i> Back</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script>\r\n");
      out.write("		const togglePassword = document.querySelector('#togglePassword');\r\n");
      out.write("		const password = document.querySelector('#password');\r\n");
      out.write("\r\n");
      out.write("		togglePassword.addEventListener('click', function() {\r\n");
      out.write("			const type = password.getAttribute('type') === 'password' ? 'text'\r\n");
      out.write("					: 'password';\r\n");
      out.write("			password.setAttribute('type', type);\r\n");
      out.write("			this.classList.toggle('bi-eye');\r\n");
      out.write("			this.classList.toggle('bi-eye-fill');\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
