/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2025-08-24 08:19:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\r\n");
      out.write("    \r\n");
      out.write("    <title>User Registration</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Poppins -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("            background: linear-gradient(120deg, #1b1b2f, #162447, #1f4068);\r\n");
      out.write("            color: white;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("        .main-container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("        /* Left card section */\r\n");
      out.write("        .left-section {\r\n");
      out.write("            flex: 0.8;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            background: #fff;\r\n");
      out.write("            animation: slideInLeft 1s ease forwards;\r\n");
      out.write("        }\r\n");
      out.write("        .register-card {\r\n");
      out.write("            background: linear-gradient(135deg, #1b1b2f, #162447, #1f4068);\r\n");
      out.write("            border-radius: 18px;\r\n");
      out.write("            padding: 20px 25px;\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            max-width: 380px;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            box-shadow: 0 10px 25px rgba(0,0,0,0.4);\r\n");
      out.write("        }\r\n");
      out.write("        .register-card h2 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 12px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: #ff4b91;\r\n");
      out.write("        }\r\n");
      out.write("        .form-label {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            margin-bottom: 3px;\r\n");
      out.write("        }\r\n");
      out.write("        .form-control {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.08);\r\n");
      out.write("            border: 1px solid rgba(255,255,255,0.25);\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            height: 38px;\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("        }\r\n");
      out.write("        .form-control:focus {\r\n");
      out.write("            border-color: #ff4b91;\r\n");
      out.write("            box-shadow: 0 0 8px rgba(255, 75, 145, 0.6);\r\n");
      out.write("        }\r\n");
      out.write("        .btn-custom {\r\n");
      out.write("            background-color: #ff4b91;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            padding: 8px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("            transition: 0.25s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-custom:hover {\r\n");
      out.write("            background-color: #ff2e75;\r\n");
      out.write("            transform: translateY(-1px);\r\n");
      out.write("        }\r\n");
      out.write("        .btn-outline-light {\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            padding: 8px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Right text section */\r\n");
      out.write("        .right-section {\r\n");
      out.write("            flex: 1.2;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            justify-content: center; \r\n");
      out.write("            align-items: center;     \r\n");
      out.write("            padding: 40px;\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            animation: slideInRight 1s ease forwards;\r\n");
      out.write("        }\r\n");
      out.write("        .right-section h1 {\r\n");
      out.write("            font-size: 2.4rem;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: #ff4b91;\r\n");
      out.write("            margin-bottom: 12px;\r\n");
      out.write("        }\r\n");
      out.write("        .right-section p {\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            color: #f0f0f0;\r\n");
      out.write("            line-height: 1.5;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Animations */\r\n");
      out.write("        @keyframes slideInLeft {\r\n");
      out.write("            from { transform: translateX(-100%); opacity: 0; }\r\n");
      out.write("            to { transform: translateX(0); opacity: 1; }\r\n");
      out.write("        }\r\n");
      out.write("        @keyframes slideInRight {\r\n");
      out.write("            from { transform: translateX(100%); opacity: 0; }\r\n");
      out.write("            to { transform: translateX(0); opacity: 1; }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"main-container\">\r\n");
      out.write("    <!-- Left side Register Card -->\r\n");
      out.write("    <div class=\"left-section\">\r\n");
      out.write("        <div class=\"register-card\">\r\n");
      out.write("            <h2>Register</h2>\r\n");
      out.write("            <form id=\"registerForm\" action=\"Registerserv\" method=\"post\" onsubmit=\"return finalValidate()\">\r\n");
      out.write("\r\n");
      out.write("                <!-- Port ID -->\r\n");
      out.write("                <div class=\"mb-2\">\r\n");
      out.write("                    <label for=\"port_id\" class=\"form-label\">Port ID</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"port_id\" name=\"port_id\" required>\r\n");
      out.write("\r\n");
      out.write("                    <small class=\"text-danger\">\r\n");
      out.write("                        ");
      out.print( (request.getAttribute("portIdError") != null) ? request.getAttribute("portIdError") : "" );
      out.write("\r\n");
      out.write("                    </small>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Full Name -->\r\n");
      out.write("                <div class=\"mb-2\">\r\n");
      out.write("                    <label for=\"name\" class=\"form-label\">Full Name</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"name\" name=\"name\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Email -->\r\n");
      out.write("                <div class=\"mb-2\">\r\n");
      out.write("                    <label for=\"email\" class=\"form-label\">Email</label>\r\n");
      out.write("                    <input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" required oninput=\"validateEmail(this)\">\r\n");
      out.write("                    <div id=\"emailHelp\" class=\"form-text text-danger d-none\">Invalid Email Format!</div>\r\n");
      out.write("                    <small class=\"text-danger\">\r\n");
      out.write("                        ");
      out.print( (request.getAttribute("emailError") != null) ? request.getAttribute("emailError") : "" );
      out.write("\r\n");
      out.write("                    </small>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("               <!-- Password -->\r\n");
      out.write("<div class=\"mb-2 position-relative\">\r\n");
      out.write("    <label for=\"password\" class=\"form-label\">Password</label>\r\n");
      out.write("    <input type=\"password\" class=\"form-control\" id=\"password\" name=\"password\" required oninput=\"validatePassword(this)\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Eye icon inside input -->\r\n");
      out.write("    <span id=\"togglePassword\" style=\"position:absolute; right:10px; top:38px; cursor:pointer; color:#ff4b91;\">\r\n");
      out.write("        <i class=\"fa-solid fa-eye\"></i>\r\n");
      out.write("    </span>\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"passwordHelp\" class=\"form-text text-danger d-none\">\r\n");
      out.write("        Password must be 8 chars, include uppercase, lowercase, number & special char!\r\n");
      out.write("    </div>\r\n");
      out.write("    <small class=\"text-danger\">\r\n");
      out.write("        ");
      out.print( (request.getAttribute("passwordError") != null) ? request.getAttribute("passwordError") : "" );
      out.write("\r\n");
      out.write("    </small>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- Location -->\r\n");
      out.write("                <div class=\"mb-2\">\r\n");
      out.write("                    <label for=\"location\" class=\"form-label\">Location</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"location\" name=\"location\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-custom w-100 mb-2\" id=\"registerBtn\" disabled>Register</button>\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("            <!-- Already Registered Button -->\r\n");
      out.write("            <a href=\"login.jsp\" class=\"btn btn-outline-light w-100\">Already Registered? Login</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Right side text -->\r\n");
      out.write("    <div class=\"right-section\">\r\n");
      out.write("        <h1>Join Us Today</h1>\r\n");
      out.write("        <p>\r\n");
      out.write("            Create your account to explore our Import Export ERP System.<br>\r\n");
      out.write("            Get access to powerful tools, manage your ports, and grow your business with ease.\r\n");
      out.write("        </p>\r\n");
      out.write("\r\n");
      out.write("        <!-- Added Image -->\r\n");
      out.write("        <img src=\"https://static.vecteezy.com/system/resources/previews/002/788/767/non_2x/woman-sitting-table-with-laptop-working-on-a-computer-freelance-online-education-or-social-media-concept-freelance-or-studying-concept-flat-style-illustration-isolated-on-white-vector.jpg\" alt=\"ERP Illustration\" \r\n");
      out.write("             class=\"img-fluid mt-3 rounded shadow\" style=\"max-width: 350px;\">\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function validateEmail(input) {\r\n");
      out.write("    const emailPattern = /^[a-zA-Z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,4}$/;\r\n");
      out.write("    const helpText = document.getElementById(\"emailHelp\");\r\n");
      out.write("    if (!emailPattern.test(input.value)) {\r\n");
      out.write("        helpText.classList.remove(\"d-none\");\r\n");
      out.write("        return false;\r\n");
      out.write("    } else {\r\n");
      out.write("        helpText.classList.add(\"d-none\");\r\n");
      out.write("        return true;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validatePassword(input) {\r\n");
      out.write("    // Password must be exactly 8 chars, with at least 1 uppercase, 1 lowercase, 1 number, 1 special char\r\n");
      out.write("    const passPattern = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@#$%^&+=!]).{8}$/;\r\n");
      out.write("    const helpText = document.getElementById(\"passwordHelp\");\r\n");
      out.write("\r\n");
      out.write("    if (!passPattern.test(input.value)) {\r\n");
      out.write("        helpText.classList.remove(\"d-none\");\r\n");
      out.write("        helpText.textContent = \"Password must be 8 chars, include uppercase, lowercase, number & special char!\";\r\n");
      out.write("        return false;\r\n");
      out.write("    } else {\r\n");
      out.write("        helpText.classList.add(\"d-none\");\r\n");
      out.write("        return true;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function finalValidate() {\r\n");
      out.write("    let emailValid = validateEmail(document.getElementById(\"email\"));\r\n");
      out.write("    let passValid = validatePassword(document.getElementById(\"password\"));\r\n");
      out.write("    return emailValid && passValid;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Enable Register button only if fields are valid\r\n");
      out.write("const formInputs = document.querySelectorAll(\"#registerForm input\");\r\n");
      out.write("const registerBtn = document.getElementById(\"registerBtn\");\r\n");
      out.write("\r\n");
      out.write("formInputs.forEach(input => {\r\n");
      out.write("    input.addEventListener(\"input\", () => {\r\n");
      out.write("        if (finalValidate() &&\r\n");
      out.write("            document.getElementById(\"port_id\").value.trim() !== \"\" &&\r\n");
      out.write("            document.getElementById(\"name\").value.trim() !== \"\" &&\r\n");
      out.write("            document.getElementById(\"location\").value.trim() !== \"\") {\r\n");
      out.write("            registerBtn.disabled = false;\r\n");
      out.write("        } else {\r\n");
      out.write("            registerBtn.disabled = true;\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("const togglePassword = document.getElementById(\"togglePassword\");\r\n");
      out.write("const passwordInput = document.getElementById(\"password\");\r\n");
      out.write("\r\n");
      out.write("togglePassword.addEventListener(\"click\", () => {\r\n");
      out.write("    const icon = togglePassword.querySelector(\"i\");\r\n");
      out.write("    if (passwordInput.type === \"password\") {\r\n");
      out.write("        passwordInput.type = \"text\";\r\n");
      out.write("        icon.classList.remove(\"fa-eye\");\r\n");
      out.write("        icon.classList.add(\"fa-eye-slash\");\r\n");
      out.write("    } else {\r\n");
      out.write("        passwordInput.type = \"password\";\r\n");
      out.write("        icon.classList.remove(\"fa-eye-slash\");\r\n");
      out.write("        icon.classList.add(\"fa-eye\");\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
