/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-01-30 09:20:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import model.User;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    User user = (User) request.getAttribute("user");
    String msg = (String) request.getAttribute("msg");

    if(user == null){
        // If someone tries to access JSP directly, redirect to servlet
        response.sendRedirect("ProfileController");
        return;
    }

    String portId = user.getPortId();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Profile Management</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("/* Body and Background */\r\n");
      out.write("body {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    font-family: 'Poppins', sans-serif;\r\n");
      out.write("    background: linear-gradient(135deg, #1b1b2f, #162447 40%, #1f4068 75%);\r\n");
      out.write("    color: white;\r\n");
      out.write("    min-height: 100vh;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Navbar */\r\n");
      out.write(".navbar {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    background: linear-gradient(90deg, #2a1a5e, #451952);\r\n");
      out.write("    padding: 20px 50px;\r\n");
      out.write("    height: 100px;\r\n");
      out.write("    position: sticky;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    z-index: 1000;\r\n");
      out.write("    box-shadow: 0 4px 20px rgba(0, 0, 0, 0.6);\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    letter-spacing: 1.2px;\r\n");
      out.write("}\r\n");
      out.write(".navbar .logo {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    font-size: 2.2rem;\r\n");
      out.write("    color: #ff4b91;\r\n");
      out.write("    letter-spacing: 1px;\r\n");
      out.write("    user-select: none;\r\n");
      out.write("}\r\n");
      out.write(".navbar .logo img {\r\n");
      out.write("    height: 75px;\r\n");
      out.write("    width: 75px;\r\n");
      out.write("    margin-right: 15px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    box-shadow: 0 4px 20px rgba(255, 75, 145, 0.8);\r\n");
      out.write("    border: 2px solid rgba(255, 255, 255, 0.4);\r\n");
      out.write("    transition: transform 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write(".navbar .logo img:hover {\r\n");
      out.write("    transform: rotate(10deg) scale(1.1);\r\n");
      out.write("}\r\n");
      out.write(".nav-links {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    gap: 50px;\r\n");
      out.write("}\r\n");
      out.write(".nav-links a {\r\n");
      out.write("    color: #f8f8f8;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    font-size: 1.15rem;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("    padding: 8px 0;\r\n");
      out.write("}\r\n");
      out.write(".nav-links a::after {\r\n");
      out.write("    content: '';\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    width: 0%;\r\n");
      out.write("    height: 3px;\r\n");
      out.write("    background: #ff4b91;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    bottom: -8px;\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("    border-radius: 2px;\r\n");
      out.write("}\r\n");
      out.write(".nav-links a:hover {\r\n");
      out.write("    color: #ff4b91;\r\n");
      out.write("}\r\n");
      out.write(".nav-links a:hover::after {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write(".btn-profile { \r\n");
      out.write("    padding: 10px 20px; \r\n");
      out.write("    border-radius: 12px; \r\n");
      out.write("    font-weight: 700; \r\n");
      out.write("    font-size: .95rem; \r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    text-decoration: none; \r\n");
      out.write("    border: none; \r\n");
      out.write("    background: linear-gradient(135deg, #ff00cc, #3333ff); \r\n");
      out.write("    color: #fff;\r\n");
      out.write("    display: flex; \r\n");
      out.write("    align-items: center; \r\n");
      out.write("    gap: 8px;\r\n");
      out.write("    box-shadow: 0 0 12px rgba(255,0,204,0.6); \r\n");
      out.write("    transition: all 0.35s ease;\r\n");
      out.write("}\r\n");
      out.write(".btn-profile:hover { \r\n");
      out.write("    transform: scale(1.07); \r\n");
      out.write("    box-shadow: 0 6px 25px rgba(255,0,204,0.6); \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Container */\r\n");
      out.write(".container {\r\n");
      out.write("    max-width: 620px;\r\n");
      out.write("    margin: 70px auto 80px;\r\n");
      out.write("    padding: 35px 40px 45px;\r\n");
      out.write("    background: rgba(255, 255, 255, 0.07);\r\n");
      out.write("    backdrop-filter: blur(20px);\r\n");
      out.write("    border-radius: 25px;\r\n");
      out.write("    border: 1.5px solid rgba(255, 255, 255, 0.15);\r\n");
      out.write("    box-shadow: 0 10px 35px rgba(0, 0, 0, 0.5);\r\n");
      out.write("    user-select: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Profile picture */\r\n");
      out.write(".profile-pic {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write(".profile-pic img {\r\n");
      out.write("    width: 130px;\r\n");
      out.write("    height: 130px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    border: 4px solid #ff4b91;\r\n");
      out.write("    box-shadow:\r\n");
      out.write("        0 0 20px #ff4b91,\r\n");
      out.write("        0 0 40px #ff4b91,\r\n");
      out.write("        0 0 70px #ff4b91;\r\n");
      out.write("    transition: transform 0.35s ease;\r\n");
      out.write("}\r\n");
      out.write(".profile-pic img:hover {\r\n");
      out.write("    transform: scale(1.12) rotate(5deg);\r\n");
      out.write("    box-shadow:\r\n");
      out.write("        0 0 25px #ff72a3,\r\n");
      out.write("        0 0 50px #ff72a3,\r\n");
      out.write("        0 0 85px #ff72a3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Title */\r\n");
      out.write("h2 {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: #ff4b91;\r\n");
      out.write("    margin-bottom: 28px;\r\n");
      out.write("    font-size: 2.25rem;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    text-shadow: 0 3px 12px rgba(0, 0, 0, 0.35);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Table & Inputs */\r\n");
      out.write("table {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    border-collapse: separate;\r\n");
      out.write("    border-spacing: 0 15px;\r\n");
      out.write("}\r\n");
      out.write("td {\r\n");
      out.write("    padding: 12px 10px 12px 0;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    font-size: 1.05rem;\r\n");
      out.write("}\r\n");
      out.write("input[type=\"text\"],\r\n");
      out.write("input[type=\"email\"],\r\n");
      out.write("input[type=\"password\"] {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 12px 15px;\r\n");
      out.write("    border-radius: 12px;\r\n");
      out.write("    border: none;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    font-size: 1rem;\r\n");
      out.write("    background: rgba(255, 255, 255, 0.12);\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    box-shadow: inset 0 0 7px rgba(0, 0, 0, 0.25);\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("}\r\n");
      out.write("input:hover,\r\n");
      out.write("input:focus {\r\n");
      out.write("    background: rgba(255, 255, 255, 0.22);\r\n");
      out.write("    animation: glowPulse 2s infinite;\r\n");
      out.write("    transform: scale(1.05);\r\n");
      out.write("    color: #ffdde1;\r\n");
      out.write("    box-shadow:\r\n");
      out.write("        0 0 8px #ff4b91,\r\n");
      out.write("        0 0 20px #ff4b91,\r\n");
      out.write("        0 0 30px #ff72a3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Glow animation */\r\n");
      out.write("@keyframes glowPulse {\r\n");
      out.write("    0%, 100% {\r\n");
      out.write("        box-shadow: 0 0 8px #ff4b91, 0 0 20px #ff4b91, 0 0 30px #ff72a3;\r\n");
      out.write("    }\r\n");
      out.write("    50% {\r\n");
      out.write("        box-shadow: 0 0 12px #ff72a3, 0 0 28px #ff72a3, 0 0 40px #ff4b91;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Password toggle icon */\r\n");
      out.write(".password-container {\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write(".password-container i {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    right: 12px;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    transform: translateY(-50%);\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    color: #ff4b91;\r\n");
      out.write("    font-size: 1.2rem;\r\n");
      out.write("    transition: color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write(".password-container i:hover {\r\n");
      out.write("    animation: iconPulse 1.5s infinite;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Buttons */\r\n");
      out.write(".btn {\r\n");
      out.write("    padding: 13px 28px;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 35px;\r\n");
      out.write("    font-size: 1rem;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    color: white;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    transition: all 0.35s ease;\r\n");
      out.write("    margin: 8px;\r\n");
      out.write("    box-shadow: 0 6px 18px rgba(0, 0, 0, 0.25);\r\n");
      out.write("}\r\n");
      out.write(".update {\r\n");
      out.write("    background: linear-gradient(90deg, #28a745, #218838);\r\n");
      out.write("}\r\n");
      out.write(".update:hover {\r\n");
      out.write("    background: linear-gradient(90deg, #218838, #28a745);\r\n");
      out.write("    transform: translateY(-4px) scale(1.06);\r\n");
      out.write("    animation: shadowPulse 1.5s infinite;\r\n");
      out.write("}\r\n");
      out.write(".delete {\r\n");
      out.write("    background: linear-gradient(90deg, #dc3545, #c82333);\r\n");
      out.write("}\r\n");
      out.write(".delete:hover {\r\n");
      out.write("    background: linear-gradient(90deg, #c82333, #dc3545);\r\n");
      out.write("    transform: translateY(-4px) scale(1.06);\r\n");
      out.write("    animation: shadowPulse 1.5s infinite;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Back button */\r\n");
      out.write(".back-btn {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    margin: 35px auto 0;\r\n");
      out.write("    padding: 12px 26px;\r\n");
      out.write("    background: #ff4b91;\r\n");
      out.write("    color: white;\r\n");
      out.write("    border-radius: 25px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("    box-shadow: 0 6px 15px rgba(255, 75, 145, 0.5);\r\n");
      out.write("    user-select: none;\r\n");
      out.write("    font-size: 1.1rem;\r\n");
      out.write("}\r\n");
      out.write(".back-btn i {\r\n");
      out.write("    margin-right: 8px;\r\n");
      out.write("}\r\n");
      out.write(".back-btn:hover {\r\n");
      out.write("    background: #ff2e75;\r\n");
      out.write("    transform: scale(1.08);\r\n");
      out.write("    animation: shadowPulse 1.8s infinite;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Animations */\r\n");
      out.write("@keyframes shadowPulse {\r\n");
      out.write("    0%, 100% {\r\n");
      out.write("        box-shadow: 0 6px 18px rgba(255, 75, 145, 0.6);\r\n");
      out.write("    }\r\n");
      out.write("    50% {\r\n");
      out.write("        box-shadow: 0 12px 25px rgba(255, 114, 163, 0.9);\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("@keyframes iconPulse {\r\n");
      out.write("    0%, 100% { color: #ff4b91; }\r\n");
      out.write("    50% { color: #ff72a3; }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive */\r\n");
      out.write("@media (max-width: 700px) {\r\n");
      out.write("    .navbar {\r\n");
      out.write("        padding: 20px 25px;\r\n");
      out.write("        flex-wrap: wrap;\r\n");
      out.write("        height: auto;\r\n");
      out.write("    }\r\n");
      out.write("    .nav-links {\r\n");
      out.write("        gap: 30px;\r\n");
      out.write("        margin-top: 10px;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("    }\r\n");
      out.write("    .container {\r\n");
      out.write("        margin: 40px 20px 60px;\r\n");
      out.write("        padding: 30px 25px 35px;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"navbar\">\r\n");
      out.write("    <div class=\"logo\">\r\n");
      out.write("       <img src=\"image/logo.png\" alt=\"Logo\">\r\n");
      out.write("       <span>ImportExportERP</span>\r\n");
      out.write("    </div>\r\n");
      out.write("       <div class=\"nav-links\">\r\n");
      out.write("        <a href=\"http://localhost:8080/RegistrationLogin/dashboard.jsp?port_id=");
      out.print( portId );
      out.write("\" class=\"nav-link\">Home</a>\r\n");
      out.write("       <a href=\"http://localhost:8080/ProductManagement/ProductServlet\" class=\"nav-link\">\r\n");
      out.write("    Product Management\r\n");
      out.write("</a>\r\n");
      out.write("        <a href=\"http://localhost:8080/OrderManagement/ListOrdersServlet?seller_port_id=");
      out.print( portId);
      out.write("\" class=\"nav-link\">\r\n");
      out.write("    Order Management\r\n");
      out.write("</a>\r\n");
      out.write("        <a href=\"http://localhost:8080/Report_product/ReportedProductsServlet?port_id=");
      out.print( portId);
      out.write("\" class=\"nav-link\">\r\n");
      out.write("    Reported Products\r\n");
      out.write("</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"nav-cta\">\r\n");
      out.write("        <a href=\"http://localhost:8080/ProfileManagement/ProfileController?port_id=");
      out.print( portId );
      out.write("\" class=\"btn btn-profile\">Profile</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"profile-pic\">\r\n");
      out.write("        <img src=\"https://cdn-icons-png.flaticon.com/512/8184/8184175.png\" alt=\"Profile Icon\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <h2>Profile Management</h2>\r\n");
      out.write("    ");
 if(msg != null){ 
      out.write("\r\n");
      out.write("        <div class=\"msg\">");
      out.print( msg );
      out.write("</div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <form method=\"post\" action=\"ProfileController\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>Port Id</td>\r\n");
      out.write("                <td><input type=\"text\" name=\"portid\" value=\"");
      out.print( user.getPortId() );
      out.write("\" readonly></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>Seller Name</td>\r\n");
      out.write("                <td><input type=\"text\" name=\"sname\" value=\"");
      out.print( user.getName() );
      out.write("\" pattern=\"[A-Za-z ]+\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>Seller Email</td>\r\n");
      out.write("                <td><input type=\"email\" name=\"semail\" value=\"");
      out.print( user.getEmail() );
      out.write("\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>Password</td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div class=\"password-container\">\r\n");
      out.write("                        <input type=\"password\" name=\"spassword\" value=\"");
      out.print( user.getPassword() );
      out.write("\" id=\"password\">\r\n");
      out.write("                        <i class=\"fas fa-eye\" id=\"togglePass\" style=\"cursor:pointer;\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>Location</td>\r\n");
      out.write("                <td><input type=\"text\" name=\"slocation\" value=\"");
      out.print( user.getLocation() );
      out.write("\" pattern=\"[A-Za-z ]+\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td colspan=\"2\" style=\"text-align:center;\">\r\n");
      out.write("                    <input type=\"submit\" name=\"update\" value=\"Update\" class=\"btn update\">\r\n");
      out.write("                    <input type=\"submit\" name=\"delete\" value=\"Delete\" class=\"btn delete\">\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("const toggle = document.getElementById('togglePass');\r\n");
      out.write("const password = document.getElementById('password');\r\n");
      out.write("toggle.addEventListener('click', () => {\r\n");
      out.write("    if(password.type === \"password\") {\r\n");
      out.write("        password.type = \"text\";\r\n");
      out.write("        toggle.classList.add('fa-eye-slash');\r\n");
      out.write("    } else {\r\n");
      out.write("        password.type = \"password\";\r\n");
      out.write("        toggle.classList.remove('fa-eye-slash');\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
