/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2025-08-23 15:49:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import model.Order;
import model.Product;
import jakarta.servlet.http.Cookie;

public final class orderDetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("model.Order");
    _jspx_imports_classes.add("model.Product");
    _jspx_imports_classes.add("jakarta.servlet.http.Cookie");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    // ✅ Cookie-based login check
    Cookie[] cookies = request.getCookies();
    String portId = null;
    if (cookies != null) {
        for (Cookie c : cookies) {
            if ("port_id".equals(c.getName())) {
                portId = c.getValue();
                break;
            }
        }
    }
    if (portId == null || portId.isEmpty()) {
        response.sendRedirect("login.jsp");
        return;
    }

      out.write('\r');
      out.write('\n');

    Order order = (Order) request.getAttribute("order");
    Product product = (Product) request.getAttribute("product");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Order Details</title>\r\n");
      out.write("<style>\r\n");
      out.write("    /* Cinematic gradient + glow */\r\n");
      out.write("    @keyframes gradientShift { 0%{background-position:0% 50%} 50%{background-position:100% 50%} 100%{background-position:0% 50%} }\r\n");
      out.write("    body{\r\n");
      out.write("        margin:0; color:#fff; font-family:'Poppins',system-ui,-apple-system,Segoe UI,Roboto,Arial;\r\n");
      out.write("        background: linear-gradient(120deg,#0f172a,#1e293b,#0b132b,#1b2a41);\r\n");
      out.write("        background-size: 300% 300%; animation: gradientShift 16s ease infinite;\r\n");
      out.write("    }\r\n");
      out.write("    .container{ max-width:1100px; margin:60px auto; padding:0 18px; }\r\n");
      out.write("    .topbar{ display:flex; justify-content:space-between; align-items:center; margin-bottom:20px; }\r\n");
      out.write("    .back{ text-decoration:none; color:#ff4b91; border:1px solid #ff4b91; padding:8px 14px; border-radius:999px; transition:.25s; }\r\n");
      out.write("    .back:hover{ background:#ff4b91; color:#fff; box-shadow:0 8px 24px rgba(255,75,145,.35); transform: translateY(-1px); }\r\n");
      out.write("\r\n");
      out.write("    .card{\r\n");
      out.write("        background: rgba(255,255,255,.06);\r\n");
      out.write("        border:1px solid rgba(255,255,255,.12);\r\n");
      out.write("        backdrop-filter: blur(10px);\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("        padding: 26px;\r\n");
      out.write("        box-shadow: 0 10px 30px rgba(0,0,0,.35);\r\n");
      out.write("        animation: fadeIn .8s ease both;\r\n");
      out.write("    }\r\n");
      out.write("    @keyframes fadeIn{ from{opacity:0; transform: translateY(16px)} to{opacity:1; transform:none} }\r\n");
      out.write("\r\n");
      out.write("    .headline{\r\n");
      out.write("        display:flex; align-items:center; gap:12px; margin:0 0 14px;\r\n");
      out.write("        font-size:28px; font-weight:700; color:#ff4b91; text-shadow:0 0 12px rgba(255,75,145,.4);\r\n");
      out.write("    }\r\n");
      out.write("    .grid{\r\n");
      out.write("        display:grid; grid-template-columns: 1.1fr .9fr; gap:22px;\r\n");
      out.write("    }\r\n");
      out.write("    .section{ padding:18px; border-radius:16px; background: rgba(255,255,255,.04); border:1px solid rgba(255,255,255,.08); }\r\n");
      out.write("    .section h3{ margin:0 0 10px; font-size:16px; letter-spacing:.4px; color:#cbd5e1; text-transform:uppercase }\r\n");
      out.write("    .kv{ display:grid; grid-template-columns: 170px 1fr; gap:10px 14px; font-size:15px; line-height:1.6 }\r\n");
      out.write("    .label{ color:#94a3b8; }\r\n");
      out.write("    .value{ color:#e2e8f0; font-weight:600 }\r\n");
      out.write("    .status{\r\n");
      out.write("        display:inline-flex; align-items:center; gap:8px; padding:6px 12px; border-radius:999px;\r\n");
      out.write("        background:#ffe08a; color:#111; font-weight:700; text-transform:uppercase; font-size:12px;\r\n");
      out.write("        box-shadow:0 0 10px rgba(255,224,138,.45);\r\n");
      out.write("    }\r\n");
      out.write("    .pill{ color:#ff4b91; font-weight:700 }\r\n");
      out.write("    .money{ font-size:22px; font-weight:800; color:#38f4c9; text-shadow:0 0 12px rgba(56,244,201,.4) }\r\n");
      out.write("\r\n");
      out.write("    /* Product showcase card */\r\n");
      out.write("    .product{\r\n");
      out.write("        display:grid; grid-template-columns: 140px 1fr; gap:16px; align-items:center;\r\n");
      out.write("        background:rgba(255,255,255,.05); border:1px solid rgba(255,255,255,.08);\r\n");
      out.write("        padding:16px; border-radius:16px; transition:.25s;\r\n");
      out.write("    }\r\n");
      out.write("    .product:hover{ transform: translateY(-3px); box-shadow:0 12px 26px rgba(0,0,0,.35)}\r\n");
      out.write("    .product .thumb{\r\n");
      out.write("        height:140px; border-radius:14px; background:\r\n");
      out.write("        linear-gradient(145deg,rgba(255,75,145,.35),rgba(56,244,201,.25));\r\n");
      out.write("        display:flex; align-items:center; justify-content:center; font-size:40px; font-weight:900;\r\n");
      out.write("        color:#fff; letter-spacing:1px;\r\n");
      out.write("    }\r\n");
      out.write("    .product .name{ font-size:20px; font-weight:700; color:#f1f5f9; margin:0 0 6px }\r\n");
      out.write("    .product .meta{ color:#cbd5e1; font-size:14px; line-height:1.7 }\r\n");
      out.write("    .product .price{ margin-top:10px; font-size:18px; font-weight:800; color:#38f4c9 }\r\n");
      out.write("\r\n");
      out.write("    .spacer{ height:20px }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"topbar\">\r\n");
      out.write("        <a class=\"back\" href=\"ListOrdersServlet\">← Back to Orders</a>\r\n");
      out.write("        <div></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <h2 class=\"headline\">Order Details</h2>\r\n");
      out.write("\r\n");
      out.write("        ");
 if (order == null) { 
      out.write("\r\n");
      out.write("            <p>Order not found.</p>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"grid\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Left: Order meta -->\r\n");
      out.write("            <div class=\"section\">\r\n");
      out.write("                <h3>Order Info</h3>\r\n");
      out.write("                <div class=\"kv\">\r\n");
      out.write("                    <div class=\"label\">Order ID</div>        <div class=\"value\">#");
      out.print( order.getOrderId() );
      out.write("</div>\r\n");
      out.write("                    <div class=\"label\">Buyer ID</div>        <div class=\"value\">");
      out.print( order.getBuyerId() );
      out.write("</div>\r\n");
      out.write("                    <div class=\"label\">Seller Port ID</div>  <div class=\"value\">");
      out.print( order.getSellerPortId() );
      out.write("</div>\r\n");
      out.write("                    <div class=\"label\">Order Date</div>      <div class=\"value\">");
      out.print( order.getOrderDate() );
      out.write("</div>\r\n");
      out.write("                    <div class=\"label\">Total Amount</div>    <div class=\"value money\">₹");
      out.print( order.getTotalAmount() );
      out.write("</div>\r\n");
      out.write("                    <div class=\"label\">Status</div>          <div class=\"value\"><span class=\"status\">");
      out.print( order.getStatus() );
      out.write("</span></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Right: Delivery -->\r\n");
      out.write("            <div class=\"section\">\r\n");
      out.write("                <h3>Delivery</h3>\r\n");
      out.write("                <div class=\"kv\">\r\n");
      out.write("                    <div class=\"label\">Address</div>\r\n");
      out.write("                    <div class=\"value\">");
      out.print( order.getDeliveryAddress() );
      out.write("</div>\r\n");
      out.write("                    <div class=\"label\">Product Ref</div>\r\n");
      out.write("                    <div class=\"value\">ID: <span class=\"pill\">#");
      out.print( order.getProductId() );
      out.write("</span></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"spacer\"></div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Product Showcase (single product from order.product_id) -->\r\n");
      out.write("        <div class=\"section\">\r\n");
      out.write("            <h3>Product</h3>\r\n");
      out.write("            ");
 if (product != null) { 
      out.write("\r\n");
      out.write("                <div class=\"product\">\r\n");
      out.write("                    <div class=\"thumb\">\r\n");
      out.write("                        ");
      out.print( (product.getProduct_name() != null && !product.getProduct_name().isEmpty())
                            ? product.getProduct_name().substring(0,1).toUpperCase()
                            : "P" );
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div class=\"name\">");
      out.print( product.getProduct_name() );
      out.write("</div>\r\n");
      out.write("                        <div class=\"meta\">\r\n");
      out.write("                            <div><strong>Seller Port:</strong> ");
      out.print( product.getSeller_port_Id() );
      out.write("</div>\r\n");
      out.write("                            <div><strong>Description:</strong> ");
      out.print( product.getDescription() );
      out.write("</div>\r\n");
      out.write("                            <div><strong>Quantity:</strong> ");
      out.print( product.getQuantity() );
      out.write("</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"price\">Price: ₹");
      out.print( product.getPrice() );
      out.write("</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                <div class=\"value\">No product found for this order.</div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
