/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2025-08-24 06:55:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import jakarta.servlet.http.Cookie;
import model.Order;

public final class updateOrders_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("model.Order");
    _jspx_imports_classes.add("jakarta.servlet.http.Cookie");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    // ✅ Cookie-based login check
    Cookie[] cookies = request.getCookies();
    String portId = null;
    if (cookies != null) {
        for (Cookie c : cookies) {
            if ("port_id".equals(c.getName())) {
                portId = c.getValue();
                break;
            }
        }
    }
    if (portId == null || portId.isEmpty()) {
        response.sendRedirect("login.jsp");
        return;
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Order Management</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Fonts -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Icons -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- SweetAlert2 -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("            background: linear-gradient(135deg, #0f2027, #203a43, #2c5364);\r\n");
      out.write("            color: white;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .wrapper { width: 100%; max-width: 600px; margin: 30px auto; }\r\n");
      out.write("        .card {\r\n");
      out.write("            background: rgba(255,255,255,0.05);\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            box-shadow: 0 8px 30px rgba(0,0,0,0.4);\r\n");
      out.write("            backdrop-filter: blur(12px);\r\n");
      out.write("        }\r\n");
      out.write("        h2 {\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            font-size: 1.4em;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("            background: linear-gradient(90deg, #ff9966, #ff5e62);\r\n");
      out.write("            -webkit-background-clip: text;\r\n");
      out.write("            -webkit-text-fill-color: transparent;\r\n");
      out.write("        }\r\n");
      out.write("        .order-detail-item {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            padding: 10px 0;\r\n");
      out.write("            border-bottom: 1px solid rgba(255,255,255,0.15);\r\n");
      out.write("        }\r\n");
      out.write("        label { margin-top: 12px; display: block; font-weight: 500; }\r\n");
      out.write("        input, select {\r\n");
      out.write("            width: 100%; padding: 12px; border-radius: 8px; border: none;\r\n");
      out.write("            margin-top: 6px; font-size: 0.95em; outline: none;\r\n");
      out.write("        }\r\n");
      out.write("        .update-btn {\r\n");
      out.write("            margin-top: 20px; padding: 14px; border: none; border-radius: 10px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            background: linear-gradient(90deg, #ff512f, #dd2476);\r\n");
      out.write("            color: white; font-size: 1.1em; font-weight: 600; cursor: pointer;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .update-btn:hover {\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("            background: linear-gradient(90deg, #dd2476, #ff512f);\r\n");
      out.write("        }\r\n");
      out.write("        .back-btn {\r\n");
      out.write("            margin-top: 15px;\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            background: linear-gradient(90deg, #2193b0, #6dd5ed);\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: 1em;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .back-btn:hover {\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("            background: linear-gradient(90deg, #6dd5ed, #2193b0);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Navbar */\r\n");
      out.write("        .navbar {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            background: linear-gradient(90deg, #2a1a5e, #451952);\r\n");
      out.write("            padding: 20px 50px;\r\n");
      out.write("            height: 100px;\r\n");
      out.write("            box-shadow: 0 4px 20px rgba(0,0,0,0.4);\r\n");
      out.write("        }\r\n");
      out.write("        .navbar .logo { display: flex; align-items: center; font-size: 2rem; font-weight: 700; color: #ff4b91; }\r\n");
      out.write("        .navbar .logo img {\r\n");
      out.write("            height: 75px; width: 75px; margin-right: 15px; border-radius: 50%;\r\n");
      out.write("            box-shadow: 0 4px 15px rgba(255, 75, 145, 0.6);\r\n");
      out.write("            border: 2px solid rgba(255,255,255,0.4);\r\n");
      out.write("        }\r\n");
      out.write("        .nav-links { display: flex; gap: 50px; }\r\n");
      out.write("        .nav-links a {\r\n");
      out.write("            color: #f8f8f8; text-decoration: none; font-weight: 500;\r\n");
      out.write("            font-size: 1.1rem; position: relative; transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-links a:hover { color: #ff4b91; }\r\n");
      out.write("        .profile-btn {\r\n");
      out.write("            background: #ff4b91; color: white; padding: 12px 20px; border-radius: 30px;\r\n");
      out.write("            font-weight: bold; text-decoration: none; display: flex; align-items: center; gap: 8px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Navbar -->\r\n");
      out.write("    <div class=\"navbar\">\r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("            <img src=\"image/logo.png\" alt=\"Logo\">\r\n");
      out.write("            <span>ImportExportERP</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"nav-links\">\r\n");
      out.write("            <a href=\"products.jsp\">Products</a>\r\n");
      out.write("            <a href=\"ListOrdersServlet\">Orders</a>\r\n");
      out.write("            <a href=\"reportedProducts.jsp\">Reported Products</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a href=\"profile.jsp\" class=\"profile-btn\"><i class=\"fas fa-user\"></i> Profile</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("        ");

            Order orderToUpdate = (Order) request.getAttribute("order");
            if (orderToUpdate != null) {
        
      out.write("\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <h2><i class=\"fas fa-edit\"></i> Update Order</h2>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"order-detail-item\">\r\n");
      out.write("                <span><i class=\"fas fa-receipt\"></i> Order ID</span>\r\n");
      out.write("                <span>#");
      out.print( orderToUpdate.getOrderId() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"order-detail-item\">\r\n");
      out.write("                <span><i class=\"fas fa-user\"></i> Buyer ID</span>\r\n");
      out.write("                <span>");
      out.print( orderToUpdate.getBuyerId() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"order-detail-item\">\r\n");
      out.write("                <span><i class=\"fas fa-store\"></i> Seller Port ID</span>\r\n");
      out.write("                <span>");
      out.print( orderToUpdate.getSellerPortId() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"order-detail-item\">\r\n");
      out.write("                <span><i class=\"fas fa-box\"></i> Product ID</span>\r\n");
      out.write("                <span>");
      out.print( orderToUpdate.getProductId() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"order-detail-item\">\r\n");
      out.write("                <span><i class=\"fas fa-calendar\"></i> Ordered On</span>\r\n");
      out.write("                <span>");
      out.print( orderToUpdate.getOrderDate() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"order-detail-item\">\r\n");
      out.write("                <span><i class=\"fas fa-dollar-sign\"></i> Total Amount</span>\r\n");
      out.write("                <span>$");
      out.print( orderToUpdate.getTotalAmount() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"order-detail-item\">\r\n");
      out.write("                <span><i class=\"fas fa-map-marker-alt\"></i> Address</span>\r\n");
      out.write("                <span>");
      out.print( orderToUpdate.getDeliveryAddress() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Update Form -->\r\n");
      out.write("            <form action=\"UpdateOrderServlet\" method=\"post\">\r\n");
      out.write("                <input type=\"hidden\" name=\"orderId\" value=\"");
      out.print( orderToUpdate.getOrderId() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                <label><i class=\"fas fa-info-circle\"></i> Order Status</label>\r\n");
      out.write("                <select name=\"status\" required>\r\n");
      out.write("                    <option value=\"Pending\"   ");
      out.print( "Pending".equalsIgnoreCase(orderToUpdate.getStatus()) ? "selected" : "" );
      out.write(">Pending</option>\r\n");
      out.write("                    <option value=\"Shipped\"   ");
      out.print( "Shipped".equalsIgnoreCase(orderToUpdate.getStatus()) ? "selected" : "" );
      out.write(">Shipped</option>\r\n");
      out.write("                    <option value=\"Delivered\" ");
      out.print( "Delivered".equalsIgnoreCase(orderToUpdate.getStatus()) ? "selected" : "" );
      out.write(">Delivered</option>\r\n");
      out.write("                    <option value=\"Cancelled\" ");
      out.print( "Cancelled".equalsIgnoreCase(orderToUpdate.getStatus()) ? "selected" : "" );
      out.write(">Cancelled</option>\r\n");
      out.write("                </select>\r\n");
      out.write("\r\n");
      out.write("                <label><i class=\"fas fa-map-marker-alt\"></i> Delivery Address</label>\r\n");
      out.write("                <input type=\"text\" name=\"deliveryAddress\" value=\"");
      out.print( orderToUpdate.getDeliveryAddress() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                <button type=\"submit\" class=\"update-btn\">\r\n");
      out.write("                    <i class=\"fas fa-save\"></i> Save Changes\r\n");
      out.write("                </button>\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("            <!-- Back to Orders Button -->\r\n");
      out.write("            <a href=\"ListOrdersServlet\" class=\"back-btn\"><i class=\"fas fa-arrow-left\"></i> Back to Orders</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- SweetAlert2 Popup Messages -->\r\n");
      out.write("    <script>\r\n");
      out.write("    (function () {\r\n");
      out.write("        const urlParams = new URLSearchParams(window.location.search);\r\n");
      out.write("        const message = urlParams.get('message');\r\n");
      out.write("        const error = urlParams.get('error');\r\n");
      out.write("\r\n");
      out.write("        if (message) {\r\n");
      out.write("            Swal.fire({\r\n");
      out.write("                icon: 'success',\r\n");
      out.write("                title: 'Updated!',\r\n");
      out.write("                text: decodeURIComponent(message),\r\n");
      out.write("                timer: 2000,\r\n");
      out.write("                showConfirmButton: false\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        if (error) {\r\n");
      out.write("            Swal.fire({\r\n");
      out.write("                icon: 'error',\r\n");
      out.write("                title: 'Update Failed',\r\n");
      out.write("                text: decodeURIComponent(error)\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    })();\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
