/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-01-30 09:19:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import jakarta.servlet.http.Cookie;
import model.Order;

public final class vieworder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("model.Order");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("jakarta.servlet.http.Cookie");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    // ✅ Cookie-based login check
    Cookie[] cookies = request.getCookies();
    String portId = null;
    if (cookies != null) {
        for (Cookie c : cookies) {
            if ("port_id".equals(c.getName())) {
                portId = c.getValue();
                break;
            }
        }
    }
    if (portId == null || portId.isEmpty()) {
        response.sendRedirect("login.jsp");
        return;
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>View Orders</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;700;800&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(":root{\r\n");
      out.write("  --bg1:#0a0214;\r\n");
      out.write("  --primary:#6c2bd9;\r\n");
      out.write("  --primary-600:#5b23c0;\r\n");
      out.write("  --primary-200:#e6dbff;\r\n");
      out.write("  --primary-100:#f6f1ff;\r\n");
      out.write("  --pink:#ff4b91;\r\n");
      out.write("  --ink:#1b1b1b;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Background animation */\r\n");
      out.write("@keyframes gradientShift{0%{background-position:0% 50%}50%{background-position:100% 50%}100%{background-position:0% 50%}}\r\n");
      out.write("html,body{height:100%}\r\n");
      out.write("body{\r\n");
      out.write("  margin:0;\r\n");
      out.write("  font-family:'Poppins',sans-serif;\r\n");
      out.write("  background:linear-gradient(120deg,#1b1b2f,#162447,#1f4068,#451952);\r\n");
      out.write("  background-size:300% 300%;\r\n");
      out.write("  animation:gradientShift 14s ease infinite;\r\n");
      out.write("  color:var(--ink);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Navbar */\r\n");
      out.write(".navbar{display:flex;justify-content:space-between;align-items:center;background:linear-gradient(90deg,#2a1a5e,#451952);padding:20px 50px;height:100px;position:sticky;top:0;z-index:30;box-shadow:0 4px 20px rgba(0,0,0,.4)}\r\n");
      out.write(".navbar .logo{display:flex;align-items:center;font-size:2rem;font-weight:700;color:#ff4b91;letter-spacing:.5px}\r\n");
      out.write(".navbar .logo img{height:75px;width:75px;margin-right:15px;border-radius:50%;box-shadow:0 4px 15px rgba(255,75,145,.6);border:2px solid rgba(255,255,255,.4)}\r\n");
      out.write(".nav-links{display:flex;gap:50px}\r\n");
      out.write(".nav-links a{color:#f8f8f8;text-decoration:none;font-weight:500;font-size:1.05rem;position:relative}\r\n");
      out.write(".nav-links a::after{content:'';position:absolute;left:0;bottom:-8px;height:3px;width:0;background:#ff4b91;border-radius:2px;transition:width .3s ease}\r\n");
      out.write(".nav-links a:hover{color:#ff4b91}\r\n");
      out.write(".nav-links a:hover::after{width:100%}\r\n");
      out.write(".btn-profile { \r\n");
      out.write("    padding: 10px 20px; \r\n");
      out.write("    border-radius: 12px; \r\n");
      out.write("    font-weight: 700; \r\n");
      out.write("    font-size: .95rem; \r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    text-decoration: none; \r\n");
      out.write("    border: none; \r\n");
      out.write("    background: linear-gradient(135deg, #ff00cc, #3333ff); \r\n");
      out.write("    color: #fff;\r\n");
      out.write("    display: flex; \r\n");
      out.write("    align-items: center; \r\n");
      out.write("    gap: 8px;\r\n");
      out.write("    box-shadow: 0 0 12px rgba(255,0,204,0.6); \r\n");
      out.write("    transition: all 0.35s ease;\r\n");
      out.write("}\r\n");
      out.write(".btn-profile:hover { \r\n");
      out.write("    transform: scale(1.07); \r\n");
      out.write("    box-shadow: 0 6px 25px rgba(255,0,204,0.6); \r\n");
      out.write("}\r\n");
      out.write("/* Page sheet */\r\n");
      out.write(".sheet{\r\n");
      out.write("  width:92%;\r\n");
      out.write("  max-width:1250px;\r\n");
      out.write("  margin:72px auto 48px;\r\n");
      out.write("  background:#fff;\r\n");
      out.write("  border:2px solid var(--primary);\r\n");
      out.write("  border-radius:16px;\r\n");
      out.write("  box-shadow:0 20px 60px rgba(0,0,0,.35);\r\n");
      out.write("  overflow:hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Header bar */\r\n");
      out.write(".sheet-head{display:flex;gap:14px;align-items:center;justify-content:space-between;padding:18px 22px;background:linear-gradient(90deg,var(--primary),#8b5cf6);color:#fff}\r\n");
      out.write(".sheet-title{font-size:1.25rem;font-weight:800;letter-spacing:.3px}\r\n");
      out.write(".tools{display:flex;gap:10px;flex-wrap:wrap}\r\n");
      out.write(".input{background:#fff;border:1.5px solid var(--primary-200);padding:10px 12px;border-radius:12px;min-width:220px;font-weight:600;color:#3c3c3c}\r\n");
      out.write(".select{appearance:none;background:#fff url('data:image/svg+xml;utf8,<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"14\" height=\"14\" viewBox=\"0 0 20 20\" fill=\"%236c2bd9\"><path d=\"M5.5 7l4.5 5 4.5-5z\"/></svg>') no-repeat right 12px center;border:1.5px solid var(--primary-200);padding:10px 36px 10px 12px;border-radius:12px;font-weight:700;color:#3c3c3c}\r\n");
      out.write(".btn{border:none;border-radius:12px;padding:10px 14px;font-weight:700;cursor:pointer;display:inline-flex;align-items:center;gap:8px;text-decoration:none}\r\n");
      out.write(".btn-purple{background:#fff;border:2px solid #b39afc;color:var(--primary)}\r\n");
      out.write(".btn-purple:hover{background:var(--primary);color:#fff}\r\n");
      out.write(".btn-print{background:transparent;border:1.5px dashed #fff;color:#fff}\r\n");
      out.write(".btn-print:hover{background:rgba(255,255,255,.1)}\r\n");
      out.write("\r\n");
      out.write("/* Table wrapper */\r\n");
      out.write(".table-wrap{max-height:68vh;overflow:auto;background:#fff}\r\n");
      out.write(".table{width:100%;border-collapse:separate;border-spacing:0}\r\n");
      out.write(".table thead th{\r\n");
      out.write("  position:sticky;top:0;z-index:5;\r\n");
      out.write("  background:var(--primary-100);color:var(--primary);\r\n");
      out.write("  font-weight:800;text-transform:uppercase;\r\n");
      out.write("  font-size:.9rem;letter-spacing:.4px;\r\n");
      out.write("  border-bottom:2px solid var(--primary-200);\r\n");
      out.write("  padding:14px 16px;\r\n");
      out.write("  text-align:center;\r\n");
      out.write("}\r\n");
      out.write(".table tbody td{\r\n");
      out.write("  border-bottom:1px solid var(--primary-200);\r\n");
      out.write("  border-right:1px solid var(--primary-200);\r\n");
      out.write("  padding:14px 16px;\r\n");
      out.write("  font-weight:600;color:#3b3b3b;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Column alignments */\r\n");
      out.write(".table td:nth-child(1), /* Order ID */\r\n");
      out.write(".table td:nth-child(2), /* Buyer ID */\r\n");
      out.write(".table td:nth-child(3), /* Seller Port ID */\r\n");
      out.write(".table td:nth-child(4), /* Product ID */\r\n");
      out.write(".table td:nth-child(5), /* Order Date */\r\n");
      out.write(".table td:nth-child(6), /* Total Amount */\r\n");
      out.write(".table td:nth-child(7)  /* Status */ {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".table td:nth-child(8){ /* Delivery Address */\r\n");
      out.write("  text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table tbody tr td:first-child{border-left:1px solid var(--primary-200)}\r\n");
      out.write(".table tbody tr:hover{background:#faf7ff}\r\n");
      out.write(".table tfoot td{padding:12px 16px;border-top:2px solid var(--primary-200);background:#fdfbff}\r\n");
      out.write("\r\n");
      out.write("/* Chips */\r\n");
      out.write(".chip{display:inline-flex;align-items:center;gap:8px;border-radius:999px;padding:6px 12px;font-size:.8rem;font-weight:800;letter-spacing:.4px;text-transform:uppercase}\r\n");
      out.write(".chip i{font-size:.9rem}\r\n");
      out.write(".chip-pending{background:#fff8e6;border:1px solid #ffe9a6;color:#795b00}\r\n");
      out.write(".chip-shipped{background:#e9fbef;border:1px solid #b8efca;color:#0f6b3d}\r\n");
      out.write(".chip-delivered{background:#eaf2ff;border:1px solid #bfd6ff;color:#0a3e91}\r\n");
      out.write(".chip-cancelled{background:#ffecee;border:1px solid #ffc3cb;color:#8c1b25}\r\n");
      out.write("\r\n");
      out.write("/* Pills */\r\n");
      out.write(".pills{display:flex;gap:8px;justify-content:center}\r\n");
      out.write(".pill{display:inline-flex;align-items:center;gap:8px;padding:8px 14px;border-radius:999px;font-weight:800;font-size:.85rem;text-decoration:none;transition:.2s}\r\n");
      out.write(".pill-view{border:2px solid #b6c9ff;color:#2452e6;background:#eef3ff}\r\n");
      out.write(".pill-edit{border:2px solid #fbb3cd;color:#d81b60;background:#fff0f6}\r\n");
      out.write("\r\n");
      out.write("/* Order link */\r\n");
      out.write(".order-link{color:#111;text-decoration:none;font-weight:800}\r\n");
      out.write(".order-link:hover{color:var(--primary)}\r\n");
      out.write("\r\n");
      out.write("/* Empty state */\r\n");
      out.write(".empty{padding:48px;text-align:center;color:#6b7280;font-weight:600}\r\n");
      out.write(".empty i{font-size:40px;color:var(--primary);margin-bottom:12px}\r\n");
      out.write("\r\n");
      out.write("/* -------- PRINT ADJUSTMENTS -------- */\r\n");
      out.write("@media print {\r\n");
      out.write("  @page { size: A4 portrait; margin: 12mm; }\r\n");
      out.write("\r\n");
      out.write("  body { background:#fff !important;-webkit-print-color-adjust: exact;print-color-adjust: exact;font-size:11px; }\r\n");
      out.write("  .navbar, .tools, .btn-print { display:none !important; }\r\n");
      out.write("\r\n");
      out.write("  .sheet { box-shadow:none;border:1px solid #000;margin:0;width:100%;transform: scale(0.95);transform-origin: top center; }\r\n");
      out.write("\r\n");
      out.write("  /* Fix table width */\r\n");
      out.write("  .table { table-layout: fixed; width: 100% !important; }\r\n");
      out.write("\r\n");
      out.write("  /* Column widths */\r\n");
      out.write("  .table th:nth-child(1), .table td:nth-child(1) { width: 7%; }\r\n");
      out.write("  .table th:nth-child(2), .table td:nth-child(2) { width: 10%; }\r\n");
      out.write("  .table th:nth-child(3), .table td:nth-child(3) { width: 10%; }\r\n");
      out.write("  .table th:nth-child(4), .table td:nth-child(4) { width: 7%; }\r\n");
      out.write("  .table th:nth-child(5), .table td:nth-child(5) { width: 16%; }\r\n");
      out.write("  .table th:nth-child(6), .table td:nth-child(6) { width: 10%; }\r\n");
      out.write("  .table th:nth-child(7), .table td:nth-child(7) { width: 12%; }\r\n");
      out.write("  .table th:nth-child(8), .table td:nth-child(8) { width: 28%; }\r\n");
      out.write("  .table th:nth-child(9), .table td:nth-child(9) { display:none !important; }\r\n");
      out.write("\r\n");
      out.write("  .table th, .table td { word-wrap: break-word;white-space: normal;font-size: 11px;padding: 8px;text-align: center; }\r\n");
      out.write("\r\n");
      out.write("  /* Print header */\r\n");
      out.write("  .print-header { display:block !important;text-align:center;margin-bottom:20px;border-bottom:2px solid #6c2bd9;padding-bottom:10px; }\r\n");
      out.write("  .print-header img { height:60px;margin-bottom:8px; }\r\n");
      out.write("  .print-header h1 { margin:0;font-size:20px;color:#6c2bd9; }\r\n");
      out.write("  .print-header p { margin:0;font-size:12px;color:#333; }\r\n");
      out.write("\r\n");
      out.write("  /* Preserve header colors */\r\n");
      out.write("  .table thead th { background:#6c2bd9 !important;color:#fff !important;-webkit-print-color-adjust: exact;print-color-adjust: exact; }\r\n");
      out.write("\r\n");
      out.write("  /* Replace status chips with plain text */\r\n");
      out.write("  .chip { all: unset !important;font-size: 11px !important;font-weight: 700 !important;color: #000 !important;text-transform: capitalize; }\r\n");
      out.write("  .chip i { display:none !important; }\r\n");
      out.write("\r\n");
      out.write("  table, tr, td, th { page-break-inside: avoid !important;break-inside: avoid !important; }\r\n");
      out.write("\r\n");
      out.write("  body::after { content: \"Page \" counter(page) \" of \" counter(pages);position: fixed;bottom: 8mm;right: 12mm;font-size: 10px;color:#333; }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Navbar -->\r\n");
      out.write("<div class=\"navbar\">\r\n");
      out.write("  <div class=\"logo\">\r\n");
      out.write("    <img src=\"image/logo.png\" alt=\"Logo\"><span>ImportExportERP</span>\r\n");
      out.write("  </div>\r\n");
      out.write("        <div class=\"nav-links\">\r\n");
      out.write("        <a href=\"http://localhost:8080/RegistrationLogin/dashboard.jsp?port_id=");
      out.print( portId );
      out.write("\" class=\"nav-link\">Home</a>\r\n");
      out.write("       <a href=\"http://localhost:8080/ProductManagement/ProductServlet\" class=\"nav-link\">\r\n");
      out.write("    Product Management\r\n");
      out.write("</a>\r\n");
      out.write("        <a href=\"http://localhost:8080/OrderManagement/ListOrdersServlet?seller_port_id=");
      out.print( portId);
      out.write("\" class=\"nav-link\">\r\n");
      out.write("    Order Management\r\n");
      out.write("</a>\r\n");
      out.write("        <a href=\"http://localhost:8080/Report_product/ReportedProductsServlet?port_id=");
      out.print( portId);
      out.write("\" class=\"nav-link\">\r\n");
      out.write("    Reported Products\r\n");
      out.write("</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"nav-cta\">\r\n");
      out.write("        <a href=\"http://localhost:8080/ProfileManagement/ProfileController?port_id=");
      out.print( portId );
      out.write("\" class=\"btn btn-profile\">Profile</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- White + Purple Sheet -->\r\n");
      out.write("<div class=\"sheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Print header -->\r\n");
      out.write("  <div class=\"print-header\" style=\"display:none;\">\r\n");
      out.write("    <img src=\"image/logo.png\" alt=\"Logo\">\r\n");
      out.write("    <h1>Orders Report</h1>\r\n");
      out.write("    <p>Generated on: ");
      out.print( new java.util.Date() );
      out.write("</p>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Sheet Header / Tools -->\r\n");
      out.write("  <div class=\"sheet-head\">\r\n");
      out.write("    <div class=\"sheet-title\"><i class=\"fa-solid fa-table-list\"></i> Seller Orders</div>\r\n");
      out.write("    <div class=\"tools\">\r\n");
      out.write("      <input id=\"q\" type=\"text\" class=\"input\" placeholder=\"Search order, buyer, address…\">\r\n");
      out.write("      <select id=\"statusFilter\" class=\"select\" title=\"Filter by status\">\r\n");
      out.write("        <option value=\"\">All Status</option>\r\n");
      out.write("        <option value=\"pending\">Pending</option>\r\n");
      out.write("        <option value=\"shipped\">Shipped</option>\r\n");
      out.write("        <option value=\"delivered\">Delivered</option>\r\n");
      out.write("        <option value=\"cancelled\">Cancelled</option>\r\n");
      out.write("      </select>\r\n");
      out.write("      <button class=\"btn btn-purple\" onclick=\"clearFilters()\"><i class=\"fa-solid fa-eraser\"></i> Clear</button>\r\n");
      out.write("      <button class=\"btn btn-print\" onclick=\"window.print()\"><i class=\"fa-solid fa-print\"></i> Print</button>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Table -->\r\n");
      out.write("  <div class=\"table-wrap\">\r\n");
      out.write("    <table class=\"table\" id=\"ordersTable\">\r\n");
      out.write("      <thead>\r\n");
      out.write("        <tr>\r\n");
      out.write("          <th>Order ID</th>\r\n");
      out.write("          <th>Buyer ID</th>\r\n");
      out.write("          <th>Seller Port ID</th>\r\n");
      out.write("          <th>Product ID</th>\r\n");
      out.write("          <th>Order Date</th>\r\n");
      out.write("          <th>Total Amount</th>\r\n");
      out.write("          <th>Status</th>\r\n");
      out.write("          <th>Delivery Address</th>\r\n");
      out.write("          <th>Actions</th>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </thead>\r\n");
      out.write("      <tbody>\r\n");
      out.write("      ");

        List<Order> orders = (List<Order>) request.getAttribute("orders");
        if (orders != null && !orders.isEmpty()) {
          for (Order order : orders) {
            String status = (order.getStatus() == null) ? "" : order.getStatus();
            String chipClass;
            if ("pending".equalsIgnoreCase(status)) chipClass = "chip-pending";
            else if ("shipped".equalsIgnoreCase(status)) chipClass = "chip-shipped";
            else if ("delivered".equalsIgnoreCase(status)) chipClass = "chip-delivered";
            else if ("cancelled".equalsIgnoreCase(status)) chipClass = "chip-cancelled";
            else chipClass = "chip-pending";
      
      out.write("\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td><a class=\"order-link\" href=\"OrderDetailsServlet?id=");
      out.print( order.getOrderId() );
      out.write('"');
      out.write('>');
      out.write('#');
      out.print( order.getOrderId() );
      out.write("</a></td>\r\n");
      out.write("          <td>");
      out.print( order.getBuyerId() );
      out.write("</td>\r\n");
      out.write("          <td>");
      out.print( order.getSellerPortId() );
      out.write("</td>\r\n");
      out.write("          <td>");
      out.print( order.getProductId() );
      out.write("</td>\r\n");
      out.write("          <td>");
      out.print( order.getOrderDate() );
      out.write("</td>\r\n");
      out.write("          <td>$");
      out.print( order.getTotalAmount() );
      out.write("</td>\r\n");
      out.write("          <td>\r\n");
      out.write("            <span class=\"chip ");
      out.print( chipClass );
      out.write("\">\r\n");
      out.write("              <i class=\"fa-solid ");
      out.print( "pending".equalsIgnoreCase(status) ? "fa-clock" :
                                   ("shipped".equalsIgnoreCase(status) ? "fa-truck" :
                                   ("delivered".equalsIgnoreCase(status) ? "fa-circle-check" : "fa-xmark")) );
      out.write("\"></i>\r\n");
      out.write("              ");
      out.print( status );
      out.write("\r\n");
      out.write("            </span>\r\n");
      out.write("          </td>\r\n");
      out.write("          <td>");
      out.print( order.getDeliveryAddress() );
      out.write("</td>\r\n");
      out.write("          <td>\r\n");
      out.write("            <div class=\"pills\">\r\n");
      out.write("              <a class=\"pill pill-view\" href=\"OrderDetailsServlet?id=");
      out.print( order.getOrderId() );
      out.write("\"><i class=\"fa-solid fa-eye\"></i> View</a>\r\n");
      out.write("              <a class=\"pill pill-edit\" href=\"UpdateOrderServlet?id=");
      out.print( order.getOrderId() );
      out.write("\"><i class=\"fa-solid fa-pen-to-square\"></i> Update</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      ");

          }
        } else {
      
      out.write("\r\n");
      out.write("        <tr><td colspan=\"9\"><div class=\"empty\"><i class=\"fa-solid fa-box-open\"></i><br>No orders found.</div></td></tr>\r\n");
      out.write("      ");

        }
      
      out.write("\r\n");
      out.write("      </tbody>\r\n");
      out.write("      <tfoot>\r\n");
      out.write("        <tr><td colspan=\"9\">Showing <span id=\"rowCount\"></span> orders</td></tr>\r\n");
      out.write("      </tfoot>\r\n");
      out.write("    </table>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("const q = document.getElementById('q');\r\n");
      out.write("const statusFilter = document.getElementById('statusFilter');\r\n");
      out.write("const table = document.getElementById('ordersTable').getElementsByTagName('tbody')[0];\r\n");
      out.write("const rowCountEl = document.getElementById('rowCount');\r\n");
      out.write("\r\n");
      out.write("function normalize(s){ return (s||'').toString().toLowerCase().trim(); }\r\n");
      out.write("function applyFilters(){\r\n");
      out.write("  const term = normalize(q.value);\r\n");
      out.write("  const status = normalize(statusFilter.value);\r\n");
      out.write("  let shown = 0;\r\n");
      out.write("  [...table.rows].forEach(tr=>{\r\n");
      out.write("    const cells = [...tr.cells].map(td => td.innerText);\r\n");
      out.write("    const rowText = normalize(cells.join(' '));\r\n");
      out.write("    const statusText = normalize(cells[6]); \r\n");
      out.write("    const matchesText = !term || rowText.includes(term);\r\n");
      out.write("    const matchesStatus = !status || statusText.includes(status);\r\n");
      out.write("    const show = matchesText && matchesStatus;\r\n");
      out.write("    tr.style.display = show ? '' : 'none';\r\n");
      out.write("    if(show) shown++;\r\n");
      out.write("  });\r\n");
      out.write("  rowCountEl.textContent = shown;\r\n");
      out.write("}\r\n");
      out.write("function clearFilters(){ q.value=''; statusFilter.value=''; applyFilters(); }\r\n");
      out.write("q.addEventListener('input', applyFilters);\r\n");
      out.write("statusFilter.addEventListener('change', applyFilters);\r\n");
      out.write("window.addEventListener('load', applyFilters);\r\n");
      out.write("\r\n");
      out.write("const wrap = document.querySelector('.table-wrap');\r\n");
      out.write("wrap.addEventListener('scroll', ()=>{\r\n");
      out.write("  const ths = document.querySelectorAll('.table thead th');\r\n");
      out.write("  const shadow = wrap.scrollTop>2 ? '0 2px 0 rgba(0,0,0,0.05)' : 'none';\r\n");
      out.write("  ths.forEach(th => th.style.boxShadow = shadow);\r\n");
      out.write("});\r\n");
      out.write("const togglePassword = document.getElementById(\"togglePassword\");\r\n");
      out.write("const passwordInput = document.getElementById(\"password\");\r\n");
      out.write("\r\n");
      out.write("togglePassword.addEventListener(\"click\", () => {\r\n");
      out.write("    const icon = togglePassword.querySelector(\"i\");\r\n");
      out.write("    if (passwordInput.type === \"password\") {\r\n");
      out.write("        passwordInput.type = \"text\";\r\n");
      out.write("        icon.classList.remove(\"fa-eye\");\r\n");
      out.write("        icon.classList.add(\"fa-eye-slash\");\r\n");
      out.write("    } else {\r\n");
      out.write("        passwordInput.type = \"password\";\r\n");
      out.write("        icon.classList.remove(\"fa-eye-slash\");\r\n");
      out.write("        icon.classList.add(\"fa-eye\");\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
